# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference

version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - run: hadolint Dockerfile

  test-app:
    docker:
      - image: golang:1.16
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            docker build -t ghcr.io/aiki-bot51/karsajobs:latest .
            docker login -u $GHCR_USERNAME -p $GHCR_TOKEN ghcr.io
            docker push ghcr.io/aiki-bot51/karsajobs:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app
